[program:game-engine-dice]
process_name=%(program_name)s
command=php /var/www/html/wango/artisan game:engine 1 --sleep=2
autostart=true
autorestart=true
startsecs=5
startretries=3
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/wango/storage/logs/game-engine-dice.log
stdout_logfile_maxbytes=10MB
stopwaitsecs=60
stopsignal=TERM
